# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'CalculatorPro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CalculatorPro
  
  # 暂时注释掉所有依赖，让工程先跑起来
  # 轻量级数学表达式解析
  # pod 'DDMathParser', '~> 2.0'
  
  # 简单存储
  # pod 'KeychainAccess', '~> 4.0'
  
  # UI布局
  # pod 'SnapKit', '~> 5.0'
  
  # 主题切换
  # pod 'SwiftTheme', '~> 0.4'
  
  # 单位转换
  # pod 'Measurement', '~> 1.0'

  target 'CalculatorProTests' do
    inherit! :search_paths
    # Pods for testing
  end
end